config/routes.rb
FakeBlockV2::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "searches/search"

  resources :searches, :only => [:index]

  resources :blocks do
    member do
      put "upvote", to: "blocks#upvote"
      put "downvote", to: "blocks#downvote"
    end
  end

  root :to => "home#index"
  get 'friends_blocks' => "home#friends_blocks", :as => :sort
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    resources :friends
    resources :private_messages

    get '/received', to: 'private_messages#received'
    get '/sent', to: 'private_messages#sent'
    put '/mark_as_read', to: 'private_messages#mark_as_read'
    get '/opened', to: 'private_messages#opened'

  end

  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :sender, foreign_key: 'sender_id', class_name:'User'
  belongs_to :receiver, foreign_key: 'receiver_id', class_name:'User'

  #validates :receiver, :presence => {:message => 'The message must have a recipient'}
  #validates :body, :presence => {:message => 'The message body cannot be blank'}
  validates_presence_of :body
  validates_presence_of :receiver_id

  end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
   before_filter :authenticate_user!

  def received
    @private_messages = PrivateMessage.where(read: false, receiver_id: current_user.id)
    @private_message = PrivateMessage.new
  end

  def opened
    @private_messages = PrivateMessage.where(read: true, receiver_id: current_user.id)
    @private_message = PrivateMessage.new
  end

  def sent
    @private_messages = PrivateMessage.where(sender_id: current_user.id)
    @private_message = PrivateMessage.new
  end

  def new
    @user||= current_user
    @private_message = PrivateMessage.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    
    @private_message = PrivateMessage.new(private_message_params)
    
    if params_receiver != nil
      receiver = params_receiver
      @private_message.receiver_id = receiver.id
    end

    if @private_message.save
      flash[:success] = 'Message was successfully sent.'
      redirect_to :back
    else
      flash[:error] = 'One of the fields was not entered correctly. Please check them.'
      redirect_to :back
    end
  end

  def show
    @pm = PrivateMessage.find(params[:id])
    @private_message = PrivateMessage.new
  end

  def mark_as_read
    message_ids = params[:messages]
    message_ids.each do |id|
      message = PrivateMessage.find(id)
      message.read = true
      message.save
    end
    redirect_to user_received_path
  end

private
 def private_message_params
      params.require(:private_message).permit(:body, :sender_id, :subject, :sent, :read)
  end

  def params_receiver
    User.where('name = ?', params[:private_message][:receiver]).first
  end
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/views/private_messages/_form.html.haml
-if current_user.present?
  = form_for [current_user, @private_message] do |f|
    .form-group
      .field
        = f.label :subject
        = f.text_field :subject, :class => 'form-control'
      .field
        = f.label "To"
        = f.text_field 'receiver', :class => 'form-control receiver'
      .field
        = f.label :body
        = f.text_area :body, :class => 'form-control'
        = f.hidden_field :sender_id, value: current_user.id
        = f.hidden_field :sent, value: Time.now
      .actions.pad-top-1
        = button_tag(:type => 'submit', :class => 'btn btn-default') do
          Send
          .fa.fa-share

app/views/private_messages/_message_nav.html.haml
%ul.nav.nav-pills.message-nav.pad-top-1
  %li
    = link_to 'Received', user_received_path(current_user)
  %li
    = link_to 'Opened', user_opened_path(current_user)
  %li
    = link_to 'Sent', user_sent_path(current_user)
  %li
    = link_to 'Compose New Message', new_user_private_message_path(current_user), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'}

app/views/private_messages/_new.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title New Message
      .modal-body
        = render partial: 'private_messages/form'

app/views/private_messages/inbox.html.haml
.content
  .row
    .col-xs-3
    .col-md-6

      %p
        .fa.fa-pencil
        = link_to 'Compose New Message', new_user_private_message_path(@user)
      %p
        = link_to 'Sent Messages', user_outbox_path(@user)

      %h3 Received Messages
      =form_tag(user_read_path, method: "put")  do
        %table.table.table-striped.table-fixed-header
          %thead.header
            %tr
              %th
                From
              %th
                Subject
              %th
                Sent
              %th
                Read
          %tbody
            - @private_messages.each do |pm|
              %tr
                %td
                  = pm.sender.name
                %td
                  = pm.subject
                %td
                  = pm.sent.to_s(:short)
                %td
                  %label.fa.fa-square-o.fa-lg{for: "message_#{pm.id}"}
                  = check_box_tag( 'messages[]', pm.id, false,  id: "message_#{pm.id}")
        =submit_tag 'Mark as Read'

app/views/private_messages/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new') %>");

app/views/private_messages/opened.html.haml
.content
  .row
    .col-xs-3
    .col-md-6
 
      =render 'message_nav'
      
      %h3 Opened Messages
      .panel
        %table.table.table-fixed-header.message-table
          %thead.header
            %tr
              %th
                From
              %th
                Subject
              %th
                Sent
          %tbody
            - @private_messages.each do |pm|
              %tr{"data-link" => user_private_message_path(:id => pm.id)}
                %td
                  = pm.sender.name
                %td.read-message{"data-link" => user_private_message_path(:id => pm.id)}
                  = pm.subject
                %td
                  = pm.sent.to_s(:short)
                

app/views/private_messages/outbox.html.haml
.content
	.row
		.col-xs-3
		.col-md-6

			%p
				.fa.fa-pencil
				= link_to 'Compose New Message', new_user_private_message_path(@user)
			%p
				= link_to 'Back to Unread Messages', user_inbox_path(@user)

			%h3 Sent Messages
			%table.table.table-striped.table-fixed-header
				%thead.header
					%tr
						%th
							To
						%th
							Subject
						%th
							Sent
				%tbody
					- @private_messages.each do |pm|
						%tr{:data-link => user_private_message_path(:id => pm.id)}
							%td
								= pm.receiver.name
							%td
								= pm.subject
							%td
								= pm.sent.to_s(:short)

app/views/private_messages/received.html.haml
.content
  .row
    .col-xs-3
    .col-md-6
 
      =render 'message_nav'

      %h3 Received Messages
      .panel
        =form_tag(user_mark_as_read_path, method: "put")  do
          %table.table.table-fixed-header.message-table
            %thead.header
              %tr
                %th
                  From
                %th
                  Subject
                %th
                  Sent
                %th
                  Read
            %tbody
              - @private_messages.each do |pm|
                %tr
                  %td
                    = pm.sender.name
                  %td.read-message{"data-link" => user_private_message_path(:id => pm.id)}
                    = pm.subject
                  %td
                    = pm.sent.to_s(:short)
                  %td
                    = check_box_tag( 'messages[]', pm.id, false,  id: "message_#{pm.id}", :class => 'check-show')
          .panel-footer
            = button_tag(:type => 'submit', :class => 'btn btn-default') do
              Mark as Read
              .fa.fa-check

app/views/private_messages/sent.html.haml
.content
  .row
    .col-xs-3
    .col-md-6
      =render 'message_nav'

      %h3 Sent Messages
      .panel
        %table.table.table-fixed-header.message-table
          %thead.header
            %tr
              %th
                To
              %th
                Subject
              %th
                Sent
          %tbody
            - @private_messages.each do |pm|
              %tr{"data-link" => user_private_message_path(:id => pm.id)}
                %td
                  = pm.receiver.name
                %td.read-message{"data-link" => user_private_message_path(:id => pm.id)}
                  = pm.subject
                %td
                  = pm.sent.to_s(:short)

app/views/private_messages/show.html.haml
.content
  .row
    .col-xs-3
    .col-md-6
      =render 'message_nav'
      
      %h3=@private_message.subject
      .panel
        %p
          %b To:
          =@pm.receiver.name
        %p
          %b Sent:
          =@pm.sent.to_s(:short)
        %p
          %b Body:
          =@pm.body