config/routes.rb
FakeBlockV2::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "searches/search"

  resources :searches, :only => [:index]

  resources :blocks do
    member do
      put "upvote", to: "blocks#upvote"
      put "downvote", to: "blocks#downvote"
    end
  end

  root :to => "home#index"
  get 'friends_blocks' => "home#friends_blocks", :as => :sort
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    resources :friends
    resources :private_messages

    get '/received', to: 'private_messages#received'
    get '/sent', to: 'private_messages#sent'
    put '/mark_as_read', to: 'private_messages#mark_as_read'
    get '/opened', to: 'private_messages#opened'

  end

  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
end

app/models/block.rb
class Block < ActiveRecord::Base
  scope :not_expired, lambda{ |time = Time.now| where("? BETWEEN created_at AND expiration OR expiration = ?", time, nil) }

  acts_as_votable
  scope :by_friends, lambda { |user| where(:user_id => user.friend_ids)}

	has_attached_file :image, 
                    :styles => { :medium => "300x300>", 
                    :thumb => "100x100>" }, 
                    :default_url => "/images/:style/missing.png",
                    :storage => :s3,
                    :bucket => 'paperclip-bucket-fake_block',
                    :s3_credentials => S3_CREDENTIALS,
                      :url => "/:image/:id/:style/:basename.:extension",
                      :path => ":image/:id/:style/:basename.:extension"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validate :any_present?
  belongs_to :user
  has_many :comments

  def expired?
    if self.expiration.present?
      if self.expiration <= Time.now
        return true
      else
        return false
      end

    else
      return false
    end
  end

  def self.delete_expired
    Block.find_each do |b|
      if b.expired?
        b.destroy
      end
    end
  end

  def expires_in seconds
    unless seconds == -1
      date_time = Time.now + (seconds).seconds
      self.expiration = date_time
    else
      self.expiration = nil
    end
  end

  def self.text_search query
    if query.present?
      where("body @@ :q or body ~* :q", q: query)
    else
      scoped
    end
  end

  def any_present?
    if %w(body image_file_name).all?{|attr| self[attr].blank?}
      errors.add :base, "Add text or an image to the block"
    end
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
    @block = Block.find(params[:id])
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  def upvote
    @block = Block.find(params[:id])
    @block.upvote_from current_user
    redirect_to :back
  end

  def downvote
    @block = Block.find(params[:id])
    @block.downvote_from current_user
    redirect_to :back
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)

    if params[:seconds_to_expiration].present?
      @block.expires_in(params[:seconds_to_expiration].to_i)
    end

    respond_to do |format|
      if @block.save
        block_partial_setup(@block)
        format.html { redirect_to :back }
        flash[:notice] = "Block posted"
        format.json { render action: 'show', status: :created, location: @block }
        format.js
      else
        format.html { render action: 'new' }
        flash[:error] = "The block couldn't be posted without an image or text."
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def block_partial_setup block
      @comment = Comment.new
    end

    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:body, :user_id, :image, :name, :viewable)
    end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_block.html.haml
-if current_user.present?  
  -if block.viewable == false || current_user.friends.include?(User.find(block.user_id)) || current_user == block.user
    .block.panel
      .form-group
        =link_to "#{block.user.name}", user_path(block.user.id)               
        %h9 - #{time_ago_in_words(block.created_at)} ago        
      .row
        .col-xs-12
          -if block.image.present?
            .block-image{"data-target" => ".modal_#{block.id}", "data-toggle" => "modal"}
              =image_tag block.image.url(:medium)
            .modal.fade.bs-example-modal-lg{class: "modal_#{block.id}","aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", role: "dialog", tabindex: "-1"}
              .modal-dialog.modal-lg
                .modal-content
                  =image_tag block.image.url
      .form-group
        %p=block.body
      .form-group
        %h9 #{block.get_upvotes.size}
        = link_to upvote_block_path(block), method: :put do
          .fa.fa-chevron-up
        |
        = link_to downvote_block_path(block), method: :put do
          .fa.fa-chevron-down
        .col-xs-3.pull-right
          -if current_user.present? && block.user == current_user
            = link_to edit_block_path(block) do
              .fa.fa-edit
            = link_to block, :method => :delete, :data => { :confirm => 'Delete permanently?' } do
              .fa.fa-times-circle-o 
      .row
        .col-xs-12
          -if block.comments.present?
            .panel-group{:id => "#accordian"}
              .panel.panel-default
                .panel-heading
                  %h4.panel-title
                    %a.accordion-toggle{"data-parent" => "#accordion", "data-toggle" => "collapse-next"}
                      Comments ...
                .panel-collapse.collapse{:id => "#collapse#{block.id}"}
                  .panel-body
                    -block.comments.order(:cached_votes_up).reverse.each do |comment|
                      .row
                        .col-xs-9
                          %p=comment.body
                        .col-xs-2
                          =link_to "#{comment.user.name}", user_path(comment.user.id)
                      .form-group
                        %h9 #{comment.get_upvotes.size}
                        = link_to upvote_comment_path(comment), method: :put do
                          .fa.fa-chevron-up
                        |
                        = link_to downvote_comment_path(comment), method: :put do
                          .fa.fa-chevron-down
      .row
        .col-xs-12
          -if current_user.present?
            =form_for @comment do |f|
              .form-group
                =f.text_area :body, :class => 'form-control'
                =f.hidden_field :block_id, value: block.id
                =f.hidden_field :user_id, value: current_user.id
              .form-group.pad-top-1
                = button_tag(:type => 'submit', :class => 'btn btn-default') do
                  comment
                  .fa.fa-share
-else       
  -if block.viewable == false
    .block.panel
      .form-group
        =link_to "#{block.user.name}", user_path(block.user.id)               
        %h9 - #{time_ago_in_words(block.created_at)} ago        
      .row
        .col-xs-12
          -if block.image.present?
            .block-image{"data-target" => ".modal_#{block.id}", "data-toggle" => "modal"}
              =image_tag block.image.url(:medium)
            .modal.fade.bs-example-modal-lg{class: "modal_#{block.id}","aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", role: "dialog", tabindex: "-1"}
              .modal-dialog.modal-lg
                .modal-content
                  =image_tag block.image.url
      .form-group
        %p=block.body
      .form-group
        %h9 #{block.get_upvotes.size}
        = link_to upvote_block_path(block), method: :put do
          .fa.fa-chevron-up
        |
        = link_to downvote_block_path(block), method: :put do
          .fa.fa-chevron-down
        .col-xs-3.pull-right
          -if @user.present? && block.user_id = @user.id
            = link_to edit_block_path(block) do
              .fa.fa-edit
            = link_to block, :method => :delete, :data => { :confirm => 'Delete permanently?' } do
              .fa.fa-times-circle-o 
      .row
        .col-xs-12
          -if block.comments.present?
            .panel-group{:id => "#accordian"}
              .panel.panel-default
                .panel-heading
                  %h4.panel-title
                    %a.accordion-toggle{"data-parent" => "#accordion", "data-toggle" => "collapse-next"}
                      Comments ...
                .panel-collapse.collapse{:id => "#collapse#{block.id}"}
                  .panel-body
                    -block.comments.order(:cached_votes_up).reverse.each do |comment|
                      .row
                        .col-xs-9
                          %p=comment.body
                        .col-xs-2
                          =link_to "#{comment.user.name}", user_path(comment.user.id)
                      .form-group
                        %h9 #{comment.get_upvotes.size}
                        = link_to upvote_comment_path(comment), method: :put do
                          .fa.fa-chevron-up
                        |
                        = link_to downvote_comment_path(comment), method: :put do
                          .fa.fa-chevron-down  

app/views/blocks/_form.html.haml
= form_for @block do |f|
  - if @block.errors.any?
    #error_explanation
      %h2= "#{pluralize(@block.errors.count, "error")} prohibited this block from being saved:"
      %ul
        - @block.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .field
      = f.label :body
      = f.text_area :body
    .actions
      = f.submit 'Save'

app/views/blocks/_post.html.haml
%h4 post something
=form_for @block, remote: true, :url => blocks_path, :html => { :multipart => true } do |f|
  =token_tag form_authenticity_token
  .form-group
    =f.text_area :body, :class => 'form-control', :id => 'block_body'
    =f.hidden_field :user_id, value: current_user.id
    .panel-group.privacy{:id => "#privacy"}
      .well.well-sm
        .panel-heading
          %a.panel-title
            %a.accordion-toggle{"data-parent" => "#privacy", "data-toggle" => "collapse-next"}
              privacy options
              .fa.fa-shield
        .panel-collapse.collapse{:id => "#collapse#privacy"}
          .panel-body
            .form-group.pad-top-1
              =f.check_box :viewable
              =f.label :viewable, "friends only", :class => 'fa fa-square-o fa-lg'
              =label_tag 'expires in'
              =select_tag :seconds_to_expiration, options_for_select([["never", 31556926],["30 seconds", 30] ,["1 minute", 60], ["30 minutes", 1800], ["1 day", 86400]])
      .row.pad-top-1
        =label_tag( 'block[image]', "", :class => 'btn btn-primary') do
          .fa.fa-camera-retro.fa-lg
        =f.file_field :image, :class => 'hide'
        = button_tag(:type => 'submit', :class => 'btn btn-default') do
          Post
          .fa.fa-share

app/views/blocks/create.js.erb
<% if @block.errors.any? -%>
  /*Hide the flash notice div*/
  $("#flash_notice").hide(300);

  /*Update the html of the div post_errors with the new one*/
  $("#block_errors").html("<%= escape_javascript(error_messages_for(@block))%>");

  /*Show the div post_errors*/
  $("#block_errors").show(300);
<% else -%>
  /*Hide the div post_errors*/
  $("#block_errors").hide(300);

  /*Update the html of the div flash_notice with the new one*/
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");

  /*Show the flash_notice div*/
  $("#flash_notice").show(300);

  /*Clear the block body*/
  $("#block_body").val("");

  $('#show_blocks').append('<%= j render(@block) %>');
<% end -%>

app/views/blocks/edit.html.haml
.content
  .col-xs-3
  .col-xs-6
    .panel
      .row
        .col-xs-1
        .col-xs-8
          %h1 Editing block
          = render 'form'
          = link_to 'Show', @block

app/views/blocks/new.html.haml
%h1 New block

= render 'form'

= link_to 'Back', blocks_path

app/views/blocks/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @block.body
%p
  %b User:
  = @block.user.name

-if current_user.present? && @block.user == current_user
  = link_to 'Edit', edit_block_path(@block)