config/routes.rb
FakeBlockV2::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "searches/search"

  resources :searches, :only => [:index]

  resources :blocks do
    member do
      put "upvote", to: "blocks#upvote"
      put "downvote", to: "blocks#downvote"
    end
  end

  root :to => "home#index"
  get 'friends_blocks' => "home#friends_blocks", :as => :sort
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    resources :friends
    resources :private_messages

    get '/received', to: 'private_messages#received'
    get '/sent', to: 'private_messages#sent'
    put '/mark_as_read', to: 'private_messages#mark_as_read'
    get '/opened', to: 'private_messages#opened'

  end

  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
end

app/models/search.rb
class Search < ActiveRecord::Base

  def self.terms_for(prefix)
    suggestions = where("term like ?", "#{prefix}_%")
    suggestions.order("popularity desc").limit(10).pluck(:term)
  end
  
  def self.index_user user
    index_term(user.name)
    user.name.split.each { |t| index_term(t) }
  end

  def self.index_users
    User.find_each do |user|
      index_term(user.name)
      user.name.split.each { |t| index_term(t) }
    end
  end

  def self.index_term(term)
    where(term: term.downcase).first_or_initialize.tap do |suggestion|
      suggestion.increment! :popularity
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    render json: Search.terms_for(params[:term])
  end

  def search
    if params[:search].present?
    	search_params = params[:search]
    	@blocks = Block.text_search(search_params)
      @users = User.text_search(search_params)
    end
  end
end

app/views/searches/search.html.haml
.col-xs-3
.col-xs-6
  .panel.center
    %h1 results
    .row
      -if @users.present?
        -@users.each do |user|
          =link_to "#{user.name}", user_path(user.id)
    .row
      .col-xs-12.center
        -if @blocks.present?
          -@blocks.each do |block|
            =block.body
            -if block.image.present?
              .block-image{"data-target" => ".modal_#{block.id}", "data-toggle" => "modal"}
                =image_tag block.image.url(:medium)
              .modal.fade.bs-example-modal-lg{class: "modal_#{block.id}","aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", role: "dialog", tabindex: "-1"}
                .modal-dialog.modal-lg
                  .modal-content
                    =image_tag block.image.url
            =link_to 'view', block_path(block.id), :class => 'btn btn-primary'
    .row
.col-xs-3