config/routes.rb
FakeBlockV2::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "searches/search"

  resources :searches, :only => [:index]

  resources :blocks do
    member do
      put "upvote", to: "blocks#upvote"
      put "downvote", to: "blocks#downvote"
    end
  end

  root :to => "home#index"
  get 'friends_blocks' => "home#friends_blocks", :as => :sort
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    resources :friends
    resources :private_messages

    get '/received', to: 'private_messages#received'
    get '/sent', to: 'private_messages#sent'
    put '/mark_as_read', to: 'private_messages#mark_as_read'
    get '/opened', to: 'private_messages#opened'

  end

  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do 
        fake block
        .fa.fa-square.fa-lg
    .collapse.navbar-collapse
      .col-xs-4
        =form_tag searches_search_path, method: 'get' do
          .input-group.search-bar
            =text_field_tag :search, params[:search], class: 'form-control search'
            %span.input-group-btn
              = button_tag(:type => 'submit', :class => 'btn btn-default') do
                .fa.fa-search
      .col-xs-6
        %ul.nav.navbar-nav
          = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li
    = link_to user_path(current_user.id) do
      = current_user.name
      .fa.fa-user
  -# %li
  -#   = link_to edit_user_registration_path do
  -#     edit account
  -#     .fa.fa-edit
  %li
    .btn-group.private-message-btn
      %button.btn.btn-inverse.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
        %span.fa.fa-envelope
      %ul.dropdown-menu{role: "menu"}
        %li
          %a
            = link_to user_received_path(current_user.id)  do
              Received Messages
        %li
          %a
            = link_to user_opened_path(current_user.id) do
              Opened Messages
        %li
          %a
            = link_to user_sent_path(current_user.id) do
              Sent Messages
        %li.divider
        %li
          %a
            = link_to 'Compose New Message', new_user_private_message_path(current_user), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'}
  %li
    .btn-group.friend-btn
      %button.btn.btn-inverse.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
        %span.fa.fa-users
      %ul.dropdown-menu{role: "menu"}
        %li
          %a
            =link_to user_friends_path(current_user.id) do
              friends list
              .fa.fa-list-alt
        %li.divider
        %li
          %a pending
          %ul
            - unless current_user.pending_friends.empty?
              - current_user.pending_friends.each do |u|
                .row
                  .col-xs-12
                    %a.pedning-friend
                      =u.name
                      =link_to user_friend_path(:user_id => current_user, :id => u), :method => :put, :confirm => 'Accept friend request! Are you sure?' do
                        .fa.fa-plus-square.fa-lg.mar-right-2
                      =link_to user_friend_path(:user_id => current_user, :id => u), :method => :delete, :confirm => 'Reject friend request! Are you sure?' do
                        .fa.fa-minus-square.fa-lg.mar-right-1

            -else
              %li
                %a no pending friend requests
        %li.divider
        %li
          %a People you may know
  %li
    = link_to destroy_user_session_path, :method=>'delete' do
      log out
      .fa.fa-sign-out
- else
  %li
    = link_to new_user_session_path do
      log in
      .fa.fa-sign-in

  %li= link_to 'Sign up', new_user_registration_path
- if current_user.present? && current_user.has_role?(:admin)
  %li= link_to 'Users', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Fake Block V2'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Fake Block V2'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
      = render partial: 'private_messages/new'
    %main{:role => "main"}
      = yield
      = render 'private_messages/new'